import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Stock Management Studio',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Sidebar />
                <div className="ml-60 p-10">
                    {children}
                </div>
            </body>
        </html>
    )
}
